### ISSUE TITLE
尝试本地部署可以加载网页但是点击没有反应

### ISSUE THREAD

**Issue by DreamGallery** [Cpk0521/WDS_Adv_Player#6]
![image](https://github.com/user-attachments/assets/307c67f5-d73f-4179-8fe7-933bcbd6c129)
无法加载素材，感觉应该不是网络问题，点击没有反应，会出现一大堆`TypeError: t.isInteractive is not a function`的错误
![image](https://github.com/user-attachments/assets/79f366b1-3fce-4c6e-85b2-1816ec8e1d2b)
想问一下部署有什么需要注意的地方吗？
另外后面我想自己测试一下有关翻译的功能，看上去似乎有接口了，但是功能没有写完？
建议翻译文件可以通过csv转换，我也会尝试自己改一下。

**Comment by Cpk0521** [comment]
看錯誤訊息 應該是無法取讀到package導致的
你可以試試用`yarn install`
如果你沒有`yarn` 可以到[官網](https://classic.yarnpkg.com/lang/en/docs/install/#windows-stable)看看

而翻譯功能 的確是沒寫完只有基礎的功能 畢竟主功能還有一堆問題...
但你依然可以像下面這樣載入翻譯
```ts
let translation = [
  {
      Id : 2000901001,
      SpeakerName : 'Kokona',
      Phrase : 'My plans for tomorrow?'
  },
  {
      Id : 2000901002,
      SpeakerName : 'Chisa',
      Phrase : 'Yeah, if you don’t have any, wanna hang out tomorrow?'
  },
  //...
]

advplayer.loadAndPlay('2000901', translation);
```

**Comment by DreamGallery** [comment]
的确，忘记yarn install了，现在没问题了

**Comment by DreamGallery** [comment]
稍微改了一下[WDS_Adv_Player](https://github.com/DreamGallery/WDS_Adv_Player)，
创了个翻译仓库[WDS-Translation-Csv](https://github.com/DreamGallery/WDS-Translation-Csv)，
从翻译仓库获取翻译文件，ts前端什么的都不是很熟，不过总算能运行了
测试的章节是1010110，就字体有点问题，感觉到时候可以换一个拼接字体或者按语言使用字体

ps:
你仓库里有两个README，一个大写文件名一个小写文件名，提交好像会出点bug🤔，倒是可以在网页上删文件

**Comment by Cpk0521** [comment]
大佬太強了

有大佬說官方的字體是改過的
![image](https://github.com/user-attachments/assets/3af60169-4d66-45be-8d63-668ece151d8c)
但我不太熟悉這方面 或許中文字體要自定義一下(?)

README那個 由於我這邊把core.ignorecase false了 所以出現這樣的問題 日後會修改

**Comment by Cpk0521** [comment]
花了點時間改了個字體 [試試看](https://cpk0521.github.io/WDS_Adv_Player/?id=1010110&tl=zhcn)

**Comment by DreamGallery** [comment]
> 花了點時間改了個字體 [試試看](https://cpk0521.github.io/WDS_Adv_Player/?id=1010110&tl=zhcn)

哇哦，大佬辛苦了。💦
效果很不错，看了下代码改了好多地方啊，之后还有其他语言的翻译的话也可以快速添加了💪。
对了，现在应该是还没有处理有关标题的翻译吧？不过这个到也不是特别重要了。

**Comment by DreamGallery** [comment]
我往我的[翻译库](https://github.com/DreamGallery/WDS-Translation-Csv)里添加了几个action工作流，
拿了[Adv-Resource](https://github.com/wds-sirius/Adv-Resource)里的episode用脚本转换了成了csv。
应该之后这边会陆续提交一些翻译，后续测试遇到问题到时候再反馈。
一周年了，希望wds再多活几年🤣
